# Generated by Django 5.0.14 on 2026-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total HT', max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, help_text='Total TVA', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, help_text='Total TTC', max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_address', models.JSONField()),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_vat_number', models.CharField(blank=True, max_length=50)),
                ('pdf_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Virement bancaire'), ('CHECK', 'Chèque'), ('CASH', 'Espèces'), ('MOCK', 'Mock (Test)')], default='MOCK', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='Référence du paiement chez le prestataire', max_length=255)),
                ('provider_data', models.JSONField(blank=True, help_text='Données brutes du prestataire', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initialisé'), ('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], db_index=True, default='INITIATED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
