# Generated by Django 5.0.14 on 2026-02-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='vehicles.vehicle')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Quantité en stock (généralement 1 pour les véhicules)')),
                ('location', models.CharField(blank=True, help_text='Emplacement physique du véhicule', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservé'), ('SOLD', 'Vendu'), ('PENDING_DELIVERY', 'En attente de livraison'), ('MAINTENANCE', 'En maintenance')], db_index=True, default='AVAILABLE', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stock véhicule',
                'verbose_name_plural': 'Stocks véhicules',
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservé'), ('SOLD', 'Vendu'), ('PENDING_DELIVERY', 'En attente de livraison'), ('MAINTENANCE', 'En maintenance')], max_length=20)),
                ('new_status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservé'), ('SOLD', 'Vendu'), ('PENDING_DELIVERY', 'En attente de livraison'), ('MAINTENANCE', 'En maintenance')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de stock',
                'verbose_name_plural': 'Logs de stock',
                'db_table': 'inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
