# Generated by Django 5.0.14 on 2026-02-05 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CAR', 'Voiture'), ('MOTORCYCLE', 'Moto'), ('UTILITY', 'Utilitaire'), ('TRUCK', 'Camion'), ('CAMPER', 'Camping-car')], db_index=True, default='CAR', max_length=20)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('mileage', models.PositiveIntegerField(help_text='Kilométrage')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Électrique'), ('HYBRID', 'Hybride'), ('PLUGIN_HYBRID', 'Hybride rechargeable'), ('LPG', 'GPL'), ('HYDROGEN', 'Hydrogène')], default='GASOLINE', max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manuelle'), ('AUTOMATIC', 'Automatique'), ('SEMI_AUTO', 'Semi-automatique')], default='MANUAL', max_length=20)),
                ('power_hp', models.PositiveIntegerField(blank=True, help_text='Puissance en chevaux', null=True)),
                ('power_kw', models.PositiveIntegerField(blank=True, help_text='Puissance en kW', null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('interior_color', models.CharField(blank=True, max_length=50)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'Neuf'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Bon'), ('FAIR', 'Correct'), ('POOR', 'À réviser')], db_index=True, default='GOOD', max_length=20)),
                ('vin', models.CharField(blank=True, help_text="Numéro d'identification du véhicule", max_length=17)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('first_registration_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicles/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Média véhicule',
                'verbose_name_plural': 'Médias véhicule',
                'db_table': 'vehicle_media',
                'ordering': ['sort_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpecification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, help_text='Groupe de spécifications', max_length=50)),
            ],
            options={
                'verbose_name': 'Spécification véhicule',
                'verbose_name_plural': 'Spécifications véhicule',
                'db_table': 'vehicle_specifications',
            },
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='history', serialize=False, to='vehicles.vehicle')),
                ('accident_history', models.TextField(blank=True, help_text='Historique des accidents')),
                ('maintenance_history', models.TextField(blank=True, help_text="Historique d'entretien")),
                ('number_of_previous_owners', models.PositiveSmallIntegerField(blank=True, help_text='Nombre de propriétaires précédents', null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_valid_until', models.DateField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('import_country', models.CharField(blank=True, max_length=100)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('service_book_available', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historique véhicule',
                'verbose_name_plural': 'Historiques véhicule',
                'db_table': 'vehicle_history',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='vehicles_brand_eef742_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price', 'is_active'], name='vehicles_price_49c780_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year', 'mileage'], name='vehicles_year_5496ce_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['category', 'condition'], name='vehicles_categor_1d830e_idx'),
        ),
        migrations.AddField(
            model_name='vehiclemedia',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclespecification',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='vehicles.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclespecification',
            unique_together={('vehicle', 'key')},
        ),
    ]
