# Generated by Django 5.0.14 on 2026-02-05 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('CONVERTED', 'Converti en commande'), ('ABANDONED', 'Abandonné'), ('EXPIRED', 'Expiré')], db_index=True, default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'db_table': 'carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text="Prix au moment de l'ajout au panier", max_digits=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article panier',
                'verbose_name_plural': 'Articles panier',
                'db_table': 'cart_items',
                'ordering': ['-added_at'],
            },
        ),
    ]
